# Generated by Django 3.0.3 on 2020-09-22 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_auto_20200923_0102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='question',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='question_text',
            new_name='topic_text',
        ),
    ]
