# Generated by Django 3.0.3 on 2020-09-22 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0004_auto_20200923_0122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='choice_text',
            new_name='reply_text',
        ),
    ]
