# Generated by Django 3.1.3 on 2020-12-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201211_1907'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Zones',
        ),
        migrations.RenameField(
            model_name='zones',
            old_name='tag',
            new_name='zone',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.CharField(default='测试', max_length=100),
            preserve_default=False,
        ),
    ]
