# Generated by Django 3.1.3 on 2020-12-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201212_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='tags',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
