# Generated by Django 3.1.3 on 2020-12-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201212_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='tags',
            field=models.CharField(blank=True, default='[]', max_length=100),
        ),
    ]
