# Generated by Django 3.1.3 on 2020-12-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201215_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
