# Generated by Django 3.0.3 on 2020-11-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='class_type',
            field=models.CharField(default='success', max_length=50),
        ),
    ]
