# Generated by Django 3.0.3 on 2020-11-06 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='updated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
