# Generated by Django 3.0.3 on 2020-11-08 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20201106_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='updated',
            new_name='duedated',
        ),
    ]
