# Generated by Django 3.0.3 on 2020-11-08 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20201108_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='duedated',
            new_name='duedate',
        ),
    ]
