# Generated by Django 3.0.3 on 2020-09-22 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_auto_20200921_0627'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Reply',
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='Topic',
        ),
    ]
