# Generated by Django 3.0.3 on 2020-10-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0008_auto_20201013_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_description',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
