# Generated by Django 3.0.3 on 2020-10-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
